version: '3.9'
services:
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./src/frontend
      args:
        REACT_APP_SERVER_PORT: ${REACT_APP_SERVER_PORT}
    container_name: app_frontend
    ports:
      - 4001:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./src/backend
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_PORT: ${DB_PORT}
        JWT_SECRET: ${JWT_SECRET}
    container_name: app_backend
    ports:
      - 4002:3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
